// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translation

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"id_ID": &dictionary{index: id_IDIndex, data: id_IDData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Hello from Sprout Digital Labs Backend": 0,
	"Invalid direction":                      3,
	"Not a piece":                            2,
	"Square is out of bounds":                1,
}

var en_USIndex = []uint32{ // 5 elements
	0x00000000, 0x00000027, 0x0000003f, 0x0000004b,
	0x0000005d,
} // Size: 44 bytes

const en_USData string = "" + // Size: 93 bytes
	"\x02Hello from Sprout Digital Labs Backend\x02Square is out of bounds" +
	"\x02Not a piece\x02Invalid direction"

var id_IDIndex = []uint32{ // 5 elements
	0x00000000, 0x00000026, 0x00000040, 0x00000053,
	0x00000064,
} // Size: 44 bytes

const id_IDData string = "" + // Size: 100 bytes
	"\x02Halo dari Sprout Digital Labs Backend\x02Kotak berada diluar batas" +
	"\x02Bukan sebuah bidak\x02Arah tidak valid"

	// Total table size 281 bytes (0KiB); checksum: DD297F5D
